require:
  - rubocop-rails
  - rubocop-performance
AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/MethodLength:
    Enabled: true
    Exclude:
      - 'db/migrate/**'